### ISSUE TITLE
Add lesson on contributing directly from Github

### ISSUE THREAD

**Issue by marwahaha** [gcapes/swc-pr-tutorial#11]
I think contributing directly from GitHub is a useful alternative to cloning and making commits from your laptop and pushing. I do it often when there are small things to fix (typos, etc).

Perhaps we could add a short lesson about it, that comes after the existing lessons.

**Comment by ha0ye** [comment]
See also the materials from @dmgt https://github.com/dmgt/swc_github_flow/blob/master/for_novice_contributors.md

**Comment by gcapes** [comment]
I'll be sure to mention this guide somewhere.
I'm not keen to encourage editing on GitHub due to the lack of a preview step, and the uninformative default commit messages it gives.
