### ISSUE TITLE
Is bundle exec worth mentioning

### ISSUE THREAD

**Issue by hoytpr** [gcapes/swc-pr-tutorial#5]
This is GREAT @gcapes and thanks for your work on this!  

As one who struggles with GitHub it was really befuddling when `make serve` didn't work on my Windows 10 machine. While trouble-shooting, I updated my gemfiles, and from there (with Ruby and the gemfiles at different versions) found no other option except to install [bundler](https://bundler.io/) and run `bundle exec jekyll serve --baseurl ''` which worked pretty much everytime. Maybe this is worth mentioning? There was a very short discussion about this on the maintainers [Slack channel](https://swcarpentry.slack.com/archives/C8H5LN44V/p1556907564009700).  

Note: I've since been able to get `make serve` to work for Carpentries lessons, but not other repos. And thanks again.

**Comment by gcapes** [comment]
Thanks!

Jekyll is an area I'm not very knowledgeable about, and I struggled with the installation first time round (even though it turned out to be very easy). I can see a failed installation being a stumbling block during the workshop.

I'll see if I can try out Jekyll on Windows and a fresh Linux system to familiarise myself with the installation process.

**Comment by gcapes** [comment]
I followed the guide here:http://carpentries.github.io/lesson-example/setup.html#optional-jekyll-setup-for-lesson-development to install ruby and jekyll on Windows. It wasn't *exactly* as in the guide (I downloaded ruby and the devkit as one installer) but it was pretty good, and I could then build a site using `jekyll serve`, so I think I'll avoid complicating thins by showing more than one option :)


I'm currently trying to get the Linux instructions made more comprehensive in https://github.com/carpentries/lesson-example/issues/260
