### ISSUE TITLE
Rebase vs Merge (lesson 03)

### ISSUE THREAD

**Issue by marwahaha** [gcapes/swc-pr-tutorial#8]
You give instructions for rebasing your branch when the `gh-pages` branch has updated.
https://gcapes.github.io/swc-pr-tutorial/03-rebase/index.html

However, I am nervous about teaching `git push -f origin feature` as a usual workflow.

I regularly give advice that novices "merge", not "rebase", so there is no possibility of losing existing commits. Then, if something "goes wrong", you can get back to the initial commits.

Could we add a section about merging as an alternative to rebasing?

**Comment by gcapes** [comment]
Thanks for raising this @marwahaha.

Merging into a feature branch always seems like a back-to-front workflow to me. However, I should add some more words of warning that rebasing changes history and when *not* to force push :) I will also mention the option of simply merging.

**Comment by gcapes** [comment]
On second thoughts, while I prefer rebasing I think I'll drop the rebasing material and just merge. There's far fewer concepts to convey :)

**Comment by gcapes** [comment]
Fixed in 50587fda8a524cdb479fe512ff30d0aa8c48524c
